### ISSUE TITLE
It seems doesn't fit 3.3.5a enUS

### ISSUE THREAD

**Issue by lixiaoquan** [nowar-fonts/Nowar-Sans#3]
After extracting fonts from release package to ${WOW}/Fonts, text on login screen can't show correctly.

Does this font package support wow 3.3.5a 12340?

**Comment by CyanoHao** [comment]
WoW 3.3.5 does not support PostScript-outlined OTF fonts, in which format Nowar Sans is shipped.

You may convert Nowar Sans to TrueType-outlined ones with [afdko](https://github.com/adobe-type-tools/afdko)'s `otf2ttf`, or try [War Sans TT](https://github.com/nowar-fonts/War-Sans-TT), which was built for non-official WotLK classic.
